### ISSUE TITLE
Please How do you use New Database

### ISSUE THREAD

**Issue by toppylawz** [Deepjyoti13/India.COVID19#1]
About https://github.com/Deepjyoti13/Django-E-Commerce.git please how do you fix the issue of new database? I noticed that when I tried using entirely new database it keeps showing the following error:

```
 File "C:\ecommerce\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\ecommerce\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\ecommerce\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\ecommerce\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\ecommerce\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\ecommerce\lib\site-packages\django\db\backends\sqlite3\base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: home_language
```

Your guide will be highly appreciated, sorry I have to ask you here since I didn't get your email. Thanks in advance

**Comment by Deepjyoti13** [comment]
Well, the same problem occurred to me. What I did was just deleted the language column from the models.py. I actually forked that repository, as you can see. I rectified few things in that and added a hell lot of new things in my repository.

**Comment by toppylawz** [comment]
Hmm thanks a lot, let me try your steps too.

**Comment by toppylawz** [comment]
Wow!! thanks a lot @Deepjyoti13 it works. You are amazing.

**Comment by Deepjyoti13** [comment]
Thanks man. Glad that I could help you in some sort or other.
Btw, http://shop.craftysane.com/ this is the website that I've built. Reload the page few times if it doesn't load in the first go.

**Comment by toppylawz** [comment]
Hello @Deepjyoti13 the website is amazing as all the functionalities seems working perfectly(I didn't test the payment). However, it will be much more lovely if you can improve the front page design. You know customers believe that when website is beautiful then it is great website(even if logic is not working, lol).

**Comment by Deepjyoti13** [comment]
I truly understand what you're saying. Ikr. The website is under developement. Hopefully the UI will look better than it is right now.
And thanks for the suggestion!

**Comment by toppylawz** [comment]
You are welcome, however please I need your help about something. I notice that when trying to 'place order' I keep seeing 
`UserProfile matching query does not exist`

It is pointing to this line:
` profile = UserProfile.objects.get(user_id=current_user.id) `

I actually thought creating a username could fix this, but it doesn't please how do you fix this?

**Comment by Deepjyoti13** [comment]
I guess, use "filter" instead of "get". Hopefully that'll do the job.
profile = UserProfile.objects.filter(user_id=current_user.id)

**Comment by Deepjyoti13** [comment]
I guess, use "filter" instead of "get". Hopefully that'll do the job.
profile = UserProfile.objects.filter(user_id=current_user.id)

**Comment by toppylawz** [comment]
Thanks a lot, i've fixed it, I realize that userprofile model must be created first in the admin dashboard before it can work.

**Comment by Deepjyoti13** [comment]
Nice to know you fixed the issue.
The same problem happened to me. I just did what I wrote in the previous comment and it worked for me.

**Comment by toppylawz** [comment]
Hello @Deepjyoti13 you seems to also create digital products on your store (http://shop.craftysane.com/) e.g craftbook, please is there any documentation (or guide from you) on how to create digital products on django? Thanks in anticipation.

**Comment by Deepjyoti13** [comment]
What do you mean by digital products? Can you elaborate?
Shame I couldn't get back to you in time. I had trouble connecting to the internet. Hope you don't mind.

**Comment by toppylawz** [comment]
Oh thanks for your feedback,  just seeing your message now, I mean products that does not require shipping(you buy and you download the product, e.g ebook). Thanks for your time brother.

**Comment by Deepjyoti13** [comment]
Ah for that purpose, do one thing. If the product is purchased by the user, it'll move to the "my orders" section. Right? There, add ```<a>```  tag in the following manner:

```<a href="/path/to/your/product" download>Download</a>```

Having done that, once a user purchased any of your digital product, he can download/view that thing from his My Orders section everytime.
Hope that works for you.

**Comment by toppylawz** [comment]
Wow!! Nice guide, I really appreciate your guide and time, I will try it.

**Comment by Deepjyoti13** [comment]
Hopefully I could solve this particular thing for you. Let me know if things didn't work as per thought.

**Comment by toppylawz** [comment]
@Deepjyoti13 So nice of you, it didn't work actually, I am trying to see a fix from [this guide](https://www.pdfdrive.com/django-12-e-commerce-e39564543.html). The topic is how to create digital product. I will keep you posted.

**Comment by Deepjyoti13** [comment]
If this guide works, fine.
Otherwise you can send me your piece of code I will surely help.
You can add a Boolean Field (is_digital) to your product model. If any product is digital, then set it to true.
Once a user buys any of your products, those products will be saved in their "My order" section.
In that "My order" section, if any product has the "is_digital" set to true than you can add a download button to that product using ```<a href='path/to/your/product' download>Download</a>```

**Comment by toppylawz** [comment]
OK brother, I really appreciate, i'll get back to you asap.

**Comment by Deepjyoti13** [comment]
Sure. Happy to help.
